In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv(r"C:\Users\mtrev\OneDrive\Desktop\Python(JN)\train.titanic.csv")

## Exploratory Data Analysis

In [4]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [6]:
df['Sex'] = df['Sex'].map({'male':1,'female':0})

In [7]:
df['Sex']

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: Sex, Length: 891, dtype: int64

In [8]:
df.drop(['Ticket','Name','Cabin'], axis=1, inplace=True)

In [9]:
df.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3    1  22.0      1      0   7.2500        S
1            2         1       1    0  38.0      1      0  71.2833        C
2            3         1       3    0  26.0      0      0   7.9250        S
3            4         1       1    0  35.0      1      0  53.1000        S
4            5         0       3    1  35.0      0      0   8.0500        S

In [10]:
df.Embarked.value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [11]:
df.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3    1  22.0      1      0   7.2500        S
1            2         1       1    0  38.0      1      0  71.2833        C
2            3         1       3    0  26.0      0      0   7.9250        S
3            4         1       1    0  35.0      1      0  53.1000        S
4            5         0       3    1  35.0      0      0   8.0500        S

In [12]:
embarked_dummy = pd.get_dummies(df['Embarked'], prefix='Embarked', dtype=int, drop_first=True)
df = pd.concat([df,embarked_dummy],axis=1)

In [13]:
df.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked  \
0            1         0       3    1  22.0      1      0   7.2500        S   
1            2         1       1    0  38.0      1      0  71.2833        C   
2            3         1       3    0  26.0      0      0   7.9250        S   
3            4         1       1    0  35.0      1      0  53.1000        S   
4            5         0       3    1  35.0      0      0   8.0500        S   

   Embarked_Q  Embarked_S  
0           0           1  
1           0           0  
2           0           1  
3           0           1  
4           0           1

In [14]:
df.drop('Embarked',axis=1,inplace=True)
df.head()
#We only see embarked for Q and S, if both columns are 0 that means it is embarked C

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  \
0            1         0       3    1  22.0      1      0   7.2500   
1            2         1       1    0  38.0      1      0  71.2833   
2            3         1       3    0  26.0      0      0   7.9250   
3            4         1       1    0  35.0      1      0  53.1000   
4            5         0       3    1  35.0      0      0   8.0500   

   Embarked_Q  Embarked_S  
0           0           1  
1           0           0  
2           0           1  
3           0           1  
4           0           1

In [15]:
df.drop('PassengerId',axis=1,inplace=True)

In [16]:
df.head(3)

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_Q  Embarked_S
0         0       3    1  22.0      1      0   7.2500           0           1
1         1       1    0  38.0      1      0  71.2833           0           0
2         1       3    0  26.0      0      0   7.9250           0           1

In [17]:
df['Fare'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 891 entries, 0 to 890
Series name: Fare
Non-Null Count  Dtype  
--------------  -----  
891 non-null    float64
dtypes: float64(1)
memory usage: 7.1 KB


In [18]:
from sklearn.preprocessing import StandardScaler

sc=StandardScaler()
df['Fare_Scaled'] = sc.fit_transform(df[['Fare']])

In [19]:
df.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_Q  Embarked_S  \
0         0       3    1  22.0      1      0   7.2500           0           1   
1         1       1    0  38.0      1      0  71.2833           0           0   
2         1       3    0  26.0      0      0   7.9250           0           1   
3         1       1    0  35.0      1      0  53.1000           0           1   
4         0       3    1  35.0      0      0   8.0500           0           1   

   Fare_Scaled  
0    -0.502445  
1     0.786845  
2    -0.488854  
3     0.420730  
4    -0.486337

In [20]:
Pclass_dummy = pd.get_dummies(df['Pclass'],prefix='Pclass',drop_first=True,dtype=int)
df = pd.concat([df,Pclass_dummy],axis=1)
df.drop('Pclass',axis=1,inplace=True)

In [21]:
df.head()

Survived  Sex   Age  SibSp  Parch     Fare  Embarked_Q  Embarked_S  \
0         0    1  22.0      1      0   7.2500           0           1   
1         1    0  38.0      1      0  71.2833           0           0   
2         1    0  26.0      0      0   7.9250           0           1   
3         1    0  35.0      1      0  53.1000           0           1   
4         0    1  35.0      0      0   8.0500           0           1   

   Fare_Scaled  Pclass_2  Pclass_3  
0    -0.502445         0         1  
1     0.786845         0         0  
2    -0.488854         0         1  
3     0.420730         0         0  
4    -0.486337         0         1

In [22]:
#Since we are going to use Logistic Regression, we will drop the reegular Fare
df.drop('Fare',axis=1,inplace=True)

In [23]:
df.head()

Survived  Sex   Age  SibSp  Parch  Embarked_Q  Embarked_S  Fare_Scaled  \
0         0    1  22.0      1      0           0           1    -0.502445   
1         1    0  38.0      1      0           0           0     0.786845   
2         1    0  26.0      0      0           0           1    -0.488854   
3         1    0  35.0      1      0           0           1     0.420730   
4         0    1  35.0      0      0           0           1    -0.486337   

   Pclass_2  Pclass_3  
0         0         1  
1         0         0  
2         0         1  
3         0         0  
4         0         1

In [24]:
df['Age'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 891 entries, 0 to 890
Series name: Age
Non-Null Count  Dtype  
--------------  -----  
714 non-null    float64
dtypes: float64(1)
memory usage: 7.1 KB


In [25]:
df.isna().sum()

Survived         0
Sex              0
Age            177
SibSp            0
Parch            0
Embarked_Q       0
Embarked_S       0
Fare_Scaled      0
Pclass_2         0
Pclass_3         0
dtype: int64

In [26]:
df['Age'].fillna(df['Age'].mean(),inplace=True)

C:\Users\mtrev\AppData\Local\Temp\ipykernel_26792\694922604.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)


In [27]:
df.isna().sum()

Survived       0
Sex            0
Age            0
SibSp          0
Parch          0
Embarked_Q     0
Embarked_S     0
Fare_Scaled    0
Pclass_2       0
Pclass_3       0
dtype: int64

## Logistic Regression

In [28]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#Features
X = df.drop('Survived',axis=1)
y = df['Survived']

#Train/test
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.3, random_state=42)

In [29]:
#initalize and train the model
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [30]:
#Predictions
y_pred = lr.predict(X_test)

print("Accuracy:", accuracy_score(y_test,y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test,y_pred))
print("Classification Report:\n", classification_report(y_test,y_pred))

Accuracy: 0.8059701492537313
Confusion Matrix:
 [[137  20]
 [ 32  79]]
Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.87      0.84       157
           1       0.80      0.71      0.75       111

    accuracy                           0.81       268
   macro avg       0.80      0.79      0.80       268
weighted avg       0.81      0.81      0.80       268



## Random Forest

In [31]:
from sklearn.ensemble import RandomForestClassifier

X = df.drop('Survived',axis=1)
y = df['Survived']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.3,random_state=42)

In [32]:
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [33]:
#Predict
y_pred_rf = rf.predict(X_test)

print("Accuracy:", accuracy_score(y_pred_rf,y_test))
print("Confusion Matrix:\n", confusion_matrix(y_pred_rf,y_test))
print("Classification Report:\n", classification_report(y_pred_rf,y_test))

Accuracy: 0.7985074626865671
Confusion Matrix:
 [[136  33]
 [ 21  78]]
Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.80      0.83       169
           1       0.70      0.79      0.74        99

    accuracy                           0.80       268
   macro avg       0.78      0.80      0.79       268
weighted avg       0.81      0.80      0.80       268



In [34]:
import xgboost as xgb

xgb_model = xgb.XGBClassifier(use_label_encoder=False, eval_metric='logloss',random_state=42)
xgb_model.fit(X_train,y_train)

E:\New folder\Python\Lib\site-packages\xgboost\training.py:183: UserWarning: [14:11:20] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [35]:
y_pred_xgb = xgb_model.predict(X_test)

print("Accuracy:", accuracy_score(y_pred_xgb, y_test))
print("Classification Matrix:\n", confusion_matrix(y_pred_xgb,y_test))
print("Clasification Report:\n", classification_report(y_pred_xgb,y_test))

Accuracy: 0.7798507462686567
Classification Matrix:
 [[130  32]
 [ 27  79]]
Clasification Report:
               precision    recall  f1-score   support

           0       0.83      0.80      0.82       162
           1       0.71      0.75      0.73       106

    accuracy                           0.78       268
   macro avg       0.77      0.77      0.77       268
weighted avg       0.78      0.78      0.78       268



In [36]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

svm = SVC()

param_grid = {} # A base version (no tuning)

grid_search = GridSearchCV(svm, param_grid, cv=5, scoring='accuracy',n_jobs=-1)

grid_search.fit(X_train,y_train)

print("Best Parameters:", grid_search.best_params_)

Best Parameters: {}


In [49]:
y_pred_svm = grid_search.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_svm))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))

Accuracy: 0.8022388059701493
Confusion Matrix:
 [[137  20]
 [ 33  78]]
              precision    recall  f1-score   support

           0       0.81      0.87      0.84       157
           1       0.80      0.70      0.75       111

    accuracy                           0.80       268
   macro avg       0.80      0.79      0.79       268
weighted avg       0.80      0.80      0.80       268



## Hyperparameter Tuning

In [50]:
#For Logistic Regression first
log_hp = LogisticRegression(max_iter=500)

#Hyperparameters
param_grid_log_hp = {
    'C':[0.01,0.1,1,10,100],
    'penalty':['l1','l2'],
    'solver':['liblinear']
}

grid_search = GridSearchCV(estimator=log_hp,param_grid=param_grid_log_hp,cv=5,scoring='accuracy')

grid_search.fit(X_train,y_train)

print("Best Parameters:", grid_search.best_params_)
print("Best Accuracy:", grid_search.best_score_)

Best Parameters: {'C': 1, 'penalty': 'l1', 'solver': 'liblinear'}
Best Accuracy: 0.8089677419354839


In [51]:
#Predictions
best_log_hp = grid_search.best_estimator_
y_pred_hp = best_log_hp.predict(X_test)

In [52]:
print("Accuracy:", accuracy_score(y_test,y_pred_hp))
print("Confusion Matrix:\n", confusion_matrix(y_test,y_pred_hp))
print(classification_report(y_test,y_pred_hp))

Accuracy: 0.8022388059701493
Confusion Matrix:
 [[137  20]
 [ 33  78]]
              precision    recall  f1-score   support

           0       0.81      0.87      0.84       157
           1       0.80      0.70      0.75       111

    accuracy                           0.80       268
   macro avg       0.80      0.79      0.79       268
weighted avg       0.80      0.80      0.80       268



## Hyperparameter Tuning for Random Forest

In [60]:
rf_hp_grid = {
    'n_estimators':[100,200], #Number of trees
    'max_depth':[None,5,10], #depth of trees
    'min_samples_split':[2,5], #min samples to split a node
    'min_samples_leaf':[1,2], #min samples at a leaf node
    'bootstrap':[True,False] #whether bootstrap samples are used
}

rf_hp = RandomForestClassifier(random_state=42)
grid_search_hp = GridSearchCV(estimator=rf_hp,param_grid=rf_hp_grid,cv=5,n_jobs=-1,scoring='accuracy')

In [61]:
grid_search_hp.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42), n_jobs=-1,
             param_grid={'bootstrap': [True, False], 'max_depth': [None, 5, 10],
                         'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 5],
                         'n_estimators': [100, 200]},
             scoring='accuracy')

In [62]:
best_rf = grid_search_hp.best_estimator_
y_pred_rf = grid_search_hp.predict(X_test)

print("Accuracy:", accuracy_score(y_test,y_pred_rf))
print("Confusion Matrix:\n", confusion_matrix(y_test,y_pred_rf))
print(classification_report(y_test,y_pred_rf))

Accuracy: 0.8171641791044776
Confusion Matrix:
 [[142  15]
 [ 34  77]]
              precision    recall  f1-score   support

           0       0.81      0.90      0.85       157
           1       0.84      0.69      0.76       111

    accuracy                           0.82       268
   macro avg       0.82      0.80      0.81       268
weighted avg       0.82      0.82      0.81       268



## Cross Validation

In [64]:
#For Logistic Regression

from sklearn.model_selection import cross_val_score
model = LogisticRegression(max_iter=1000)

#5-fold cross-validation
cv_scores = cross_val_score(model,X,y,cv=5,scoring='accuracy')

print("Cross-Validation Scores:", cv_scores)
print("Mean Accuracy:", cv_scores.mean())

Cross-Validation Scores: [0.78212291 0.80337079 0.78651685 0.76966292 0.83707865]
Mean Accuracy: 0.7957504237022157


In [67]:
#For Random Forest
rf_model = RandomForestClassifier(random_state=42)

cv_rf = cross_val_score(rf_model,X,y,cv=5,scoring='accuracy')
print("Random Forest Scores:", cv_rf.mean())

Random Forest Scores: 0.8103508882053857


In [68]:
#SVM
svm_model = SVC()
cv_svm = cross_val_score(svm_model,X,y,cv=5,scoring='accuracy')
print("SVM Scoring:", cv_svm.mean())

SVM Scoring: 0.6476052978469651
